import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "@/app/components/footer";

const rubikSans = Rubik({
  variable: "--font-rubik-sans",
  subsets: [],
});

export const metadata = {
  title: "AcopiaTech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubikSans.variable}  antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
