import { Rubik } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";

const rubikSans = Rubik({
  variable: "--font-rubik-sans",
  subsets: [],
});

export const metadata = {
  title: "AcopiaTech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubikSans.variable}  antialiased`}>
        <div>
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
